services:
  # خدمة الويب الرئيسية
  - type: web
    name: butterbakery-app
    env: node
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: butterbakery-db
          property: connectionString

databases:
  # قاعدة بيانات PostgreSQL
  - name: butterbakery-db
    plan: free
    databaseName: butterbakery
    user: butterbakery_user