services:
  - type: web
    name: butter-bakery
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: butter-bakery-db
          property: connectionString
    
databases:
  - name: butter-bakery-db
    plan: starter
    postgresMajorVersion: 15